include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_returning_null: false
    avoid_print: true
    avoid_empty_else: true
    annotate_overrides: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_positional_boolean_parameters: false